#ifndef CONFIG_H
#define CONFIG_H

typedef enum { GAME_PLAYING, GAME_OVER, GAME_VICTORY } GameState;

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 800

#define MAX_BULLETS 64
#define MAX_ENEMIES_ROWS 4
#define MAX_ENEMIES_COLS 8
#define ENEMY_BULLET_COOLDOWN 0.6f
#define ENEMY_BULLET_BASE_SPEED 2

#define MAX_ENEMIES (MAX_ENEMIES_ROWS * MAX_ENEMIES_COLS)

#define CENTER_X (SCREEN_WIDTH / 2)
#define CENTER_Y (SCREEN_HEIGHT / 2)

#define PLAYER_BULLET 0
#define PLAYER_BULLET_SPEED 340
#define PLAYER_LIFES 3
#define ENEMY_BULLET 1

#define FPS 60

#endif
