#ifndef CONFIG_H
#define CONFIG_H

typedef enum { GAME_PLAYING, GAME_OVER, GAME_VICTORY } GameState;

#define SCREEN_WIDTH 1400
#define SCREEN_HEIGHT 800

#define MAX_BULLETS 64
#define MAX_ENEMIES_ROWS 5
#define MAX_ENEMIES_COLS 16
#define ENEMY_BULLET_COOLDOWN 0.8f
#define ENEMY_BULLET_BASE_SPEED 2

#define MAX_ENEMIES (MAX_ENEMIES_ROWS * MAX_ENEMIES_COLS)

#define CENTER_X (SCREEN_WIDTH / 2)
#define CENTER_Y (SCREEN_HEIGHT / 2)

#define PLAYER_BULLET 0
#define PLAYER_BULLET_SPEED 340
#define PLAYER_LIFES 3
#define ENEMY_BULLET 1

#define MAX_PROTECTION 8
#define PROTECTION_LIFE 6
#define PROTECTION_ROW 18
#define PROTECTION_COL 18
#define PROTECTION_SCALE 3

#define FPS 60

#endif
